# -*- coding: utf-8 -*-
"""CHURN ANALYSIS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VjvTP-4mBwsjgCyg4YJ3VkND9p2kFbj2

Create Churn Prediction Model - Random Forest
"""

# Installing Libraries and Data Load

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
import joblib
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel ('/content/sample_data/Prediction_Data.xlsx',sheet_name='VW_CHURNDATA')
df.head()

# Data Preprocessing
df = df.drop(['Customer_ID','Churn_Category','Churn_Reason'], axis=1)

# List of columns to be Label Encoded
label_encode_cols = [

    'Gender', 'Married', 'State', 'Value_Deal', 'Phone_Service', 'Multiple_Lines',

    'Internet_Service', 'Internet_Type', 'Online_Security', 'Online_Backup',

    'Device_Protection_Plan', 'Premium_Support', 'Streaming_TV', 'Streaming_Movies',

    'Streaming_Music', 'Unlimited_Data', 'Contract', 'Paperless_Billing',

    'Payment_Method'

]

# Encode categorical variables except the target variable
label_encoder = {}
for col in label_encode_cols:
    label_encoder[col] = LabelEncoder()
    df[col] = label_encoder[col].fit_transform(df[col])

# Manually encode the target variable 'Customer_Status'
df['Customer_Status'] = df['Customer_Status'].map({'Stayed': 0, 'Churned': 1})

# Split data into features and target
X = df.drop('Customer_Status', axis=1)
y = df['Customer_Status']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train Random Forest Model
# Initialize the Random Forest Classifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
rf_model.fit(X_train, y_train)

# Evaluate Model
# Make predictions
y_pred = rf_model.predict(X_test)

# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Feature Selection using Feature Importance
importances = rf_model.feature_importances_
indices = np.argsort(importances)[::-1]

# Plot the feature importances
plt.figure(figsize=(15, 6))
sns.barplot(x=importances[indices], y=X.columns[indices], orient='h')
plt.xlabel('Relative Importance')
plt.ylabel('Feature Names')
plt.title('Feature Importance')
plt.show()

# Predict on New Data
new_data = pd.read_excel('/content/sample_data/Prediction_Data.xlsx', sheet_name='VW_JOINDATA')

new_data.head()

# Keep non-features columns (ID and labels)
non_feature_cols = ['Customer_ID', 'Customer_Status','Churn_Category','Churn_Reason']

# Features that the nodel will use
features = new_data.drop(columns=non_feature_cols)

# Encode only categorical features needed for the model
for col in features.select_dtypes(include=['object']).columns:
    # Use the previously saved label encoder for each column
    features[col] = label_encoder[col].transform(features[col])

# Make predictions
predictions = rf_model.predict(features)

new_data['Customer_Status_Predicted'] = predictions

# Filter only predicted churned customers
predict_churn_data = new_data[new_data['Customer_Status_Predicted'] == 1]

# Save the results
original_data.to_csv(
    r"C:\Users\Admin\Documents\Portfolio\Portfolio 5 Data Analysis Churn Analysis\predict_churn_data.csv",
    index=False
)

print(predict_churn_data.head())

from google.colab import files

files.download(
    r"C:\Users\Admin\Documents\Portfolio\Portfolio 5 Data Analysis Churn Analysis\predict_churn_data.csv"
)

